apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "policyreporter.serviceAccountName" . }}
  namespace: policy-reporter
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
