apiVersion: v1
kind: Service
metadata:
  name: {{ include "policyreporter.fullname" . }}
  namespace: policy-reporter
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "policyreporter.selectorLabels" . | nindent 4 }}
