{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "policyreporter.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.labels }}
  labels:
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }} 
  {{- end }}
spec:
  selector:
    matchLabels:
        {{- include "policyreporter.selectorLabels" . | nindent 8 }}
  endpoints:
  - port: http 
{{- end }}
