apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policyreporter.fullname" . }}-targets
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |-
    loki:
      host: {{ .Values.loki.host | quote }}
      minimumPriority: {{ .Values.loki.minimumPriority | quote }}
      skipExistingOnStartup: {{ .Values.loki.skipExistingOnStartup }}

    elasticsearch:
      host: {{ .Values.elasticsearch.host | quote }}
      index: {{ .Values.elasticsearch.index | default "policy-reporter" | quote }}
      rotation: {{ .Values.elasticsearch.rotation | default "dayli" | quote }}
      minimumPriority: {{ .Values.elasticsearch.minimumPriority | quote }}
      skipExistingOnStartup: {{ .Values.elasticsearch.skipExistingOnStartup }}

    slack:
      webhook: {{ .Values.slack.webhook | quote }}
      minimumPriority: {{ .Values.slack.minimumPriority | quote }}
      skipExistingOnStartup: {{ .Values.slack.skipExistingOnStartup }}

    discord:
      webhook: {{ .Values.discord.webhook | quote }}
      minimumPriority: {{ .Values.discord.minimumPriority | quote }}
      skipExistingOnStartup: {{ .Values.discord.skipExistingOnStartup }}
