apiVersion: v2
name: policy-reporter
description: |
  Policy Reporter watches for PolicyReport Resources.
  It creates Prometheus Metrics and can send rule validation events to different targets like Loki, Elasticsearch, Slack or Discord

type: application
version: 1.12.6
appVersion: 1.10.3

icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
home: https://github.com/kyverno/policy-reporter/wiki
sources:
  - https://github.com/kyverno/policy-reporter
maintainers:
  - name: Frank Jogeleit

dependencies:
  - name: monitoring
    condition: monitoring.enabled
    version: "1.5.0"
  - name: ui
    condition: ui.enabled
    version: "1.10.3"
  - name: kyvernoPlugin
    condition: kyvernoPlugin.enabled
    version: "0.7.1"
